from selenium import webdriver
from selenium.webdriver.common.by import By
chrome_options=webdriver.ChromeOptions()
chrome_options.add_experimental_option("detach",True)
driver=webdriver.Chrome(options=chrome_options)
test=driver.get('https://python.org')
# driver.implicitly_wait(10)
search_bar=driver.find_element(By.NAME,value="q")
print(search_bar.get_attribute("placeholder"))
button=driver.find_element(By.ID,value="submit")
print(button.size)
link=driver.find_element(By.CSS_SELECTOR,value=".documentation-widget p a")
print(link.get_attribute("href"))
print(driver.find_element(By.XPATH,value='//*[@id="content"]/div/section/div[3]/div[2]/div/ul/li[1]/b').text)
print(driver.find_elements(By.CSS_SELECTOR))
# driver.quit()
driver.quit()